# Template for e2e tests.

inputs:
  kubernetes-version:
    required: true
    type: string
  cluster_name:
    required: false
    type: string
    default: katib-e2e-cluster

runs:
  using: composite
  steps:
    - name: Set Up KinD Cluster
      uses: helm/kind-action@v1.2.0
      with:
        version: v0.13.0
        node_image: kindest/node:${{ inputs.kubernetes-version }}
        cluster_name: ${{ inputs.cluster_name }}
        wait: 120s

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set Up Go env
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.10
